export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!;
export const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT!;

export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const QUICKLINKS_ID = process.env.NEXT_PUBLIC_APPWRITE_QUICKLINKS_ID!;
export const TAXREFUND_ID = process.env.NEXT_PUBLIC_APPWRITE_TAXREFUND_ID!;
export const SERVICES_ID = process.env.NEXT_PUBLIC_APPWRITE_SERVICES_ID!;
export const CONTACT_ID = process.env.NEXT_PUBLIC_APPWRITE_CONTACT_ID!;

export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;

export const WEB3FORMS_ACCESS_KEY = process.env.WEB3FORMS_ACCESS_KEY!;